# Generated by Django 3.2.7 on 2021-10-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('engine', models.IntegerField(blank=True)),
                ('content', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mygiggs.sort')),
            ],
        ),
    ]
